import { useNavigate } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

export default function Disclaimer() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-dark-bg">
      {/* Header */}
      <div className="border-b border-border-color sticky top-0 z-40 bg-card-bg">
        <div className="container py-4">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-sm text-text-secondary hover:text-primary transition-colors"
          >
            <ChevronLeft size={16} />
            Back to Home
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="container py-12 max-w-4xl">
        <div className="space-y-8">
          <div>
            <h1 className="text-4xl font-bold text-text-primary mb-2">Disclaimer</h1>
            <p className="text-text-secondary"><strong>Last Updated:</strong> March 29, 2026</p>
          </div>

          <div className="space-y-8 text-text-secondary">
            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">1. General Disclaimer</h2>
              <p>
                The information provided by PostGenius ("Company," "we," "us," or "our") on our website and through our Service is for general informational purposes only. All information is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on our website or Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">2. No Professional Advice</h2>
              <p>PostGenius does not provide legal, financial, medical, or professional advice. The content generated by our Service is for informational purposes only and should not be construed as professional advice.</p>
              <p className="mt-4"><strong>You should not rely on our Service for:</strong></p>
              <ul className="list-disc list-inside space-y-2 ml-2 mt-2">
                <li>Legal advice (consult a licensed attorney)</li>
                <li>Financial or investment advice (consult a financial advisor)</li>
                <li>Medical or health advice (consult a healthcare professional)</li>
                <li>Tax advice (consult a tax professional)</li>
                <li>Business strategy (consult a business consultant)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">3. AI-Generated Content Disclaimer</h2>
              <p>PostGenius uses artificial intelligence to generate content. While we strive for accuracy and quality, AI-generated content may:</p>
              <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
                <li>Contain errors, inaccuracies, or outdated information</li>
                <li>Require human review and editing</li>
                <li>Not be suitable for all contexts or audiences</li>
                <li>Require fact-checking before publication</li>
              </ul>
              <p className="mt-4"><strong>You are responsible for reviewing, editing, and verifying all content before use.</strong></p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">4. No Warranty of Results</h2>
              <p>PostGenius makes no guarantee regarding:</p>
              <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
                <li>Increased sales or revenue from using our Service</li>
                <li>Improved social media engagement or followers</li>
                <li>Specific business outcomes or results</li>
                <li>Return on investment (ROI)</li>
                <li>Marketing performance or effectiveness</li>
              </ul>
              <p className="mt-4">Results vary based on many factors outside our control, including market conditions, audience, content quality, and implementation.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">5. Service Availability</h2>
              <p>PostGenius makes no warranty that:</p>
              <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
                <li>The Service will be uninterrupted or error-free</li>
                <li>Defects will be corrected</li>
                <li>The Service will be available at all times</li>
                <li>The Service is free from viruses or harmful components</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">6. User Responsibility</h2>
              <p>You are solely responsible for:</p>
              <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
                <li>Your use of the Service</li>
                <li>Compliance with applicable laws and regulations</li>
                <li>Verification of all information and content</li>
                <li>The consequences of publishing or using generated content</li>
                <li>Any claims arising from your use of the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-text-primary mb-4">7. Contact Us</h2>
              <p>If you have questions about this Disclaimer:</p>
              <div className="mt-4 p-4 bg-card-bg rounded-lg border border-border-color">
                <p><strong>Email:</strong> <a href="mailto:support@postgenius-ai.com" className="text-primary hover:text-primary-light">support@postgenius-ai.com</a></p>
                <p><strong>Website:</strong> <a href="https://postgenius-ai.com" className="text-primary hover:text-primary-light">https://postgenius-ai.com</a></p>
              </div>
            </section>

            <p className="text-text-secondary italic mt-8"><strong>IMPORTANT:</strong> By using PostGenius, you acknowledge that you have read and understood this Disclaimer and agree to be bound by its terms.</p>
          </div>
        </div>
      </div>
    </div>
  )
}
